<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="D103260" name="ACS_CRMN.WebJourney" tests="7" failures="0" timestamp="16 Aug 2012 14:10:02 GMT" time="103.135" errors="1">
  <testcase name="E_WebJourneyEdit" time="34.180" classname="ACS_CRMN.WebJourney"/>
  <testcase name="B_CheckProfile" time="10.965" classname="ACS_CRMN.WebJourney"/>
  <testcase name="F_checkProfile" time="5.476" classname="ACS_CRMN.WebJourney">
    <error type="java.lang.AssertionError" message="Profile after updation........ expected:&lt;true&gt; but was:&lt;false&gt;">
      <![CDATA[java.lang.AssertionError: Profile after updation........ expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:281)
	at ACS_CRMN.WebJourney.F_checkProfile(WebJourney.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- F_checkProfile -->
  <testcase name="C_WebJourney2" time="11.580" classname="ACS_CRMN.WebJourney"/>
  <testcase name="D_CheckEntitlement" time="5.194" classname="ACS_CRMN.WebJourney"/>
  <testcase name="A_WebJourney1" time="35.609" classname="ACS_CRMN.WebJourney"/>
  <testcase name="G_CheckEntitlement" time="0.131" classname="ACS_CRMN.WebJourney"/>
</testsuite> <!-- ACS_CRMN.WebJourney -->
